### ISSUE TITLE
Collab to have one plugin

### ISSUE THREAD

**Issue by dweber019** [konfig-dev/backstage-plugin-konfig#21]
As this repo seams to be a copy of the initial work of https://github.com/dweber019/backstage-plugin-api-docs-spectral-linter maybe we could create a plugin suitable for both use cases to minimize work?

Would you be up for it?

**Comment by dphuang2** [comment]
> As this repo seams to be a copy of the initial work of https://github.com/dweber019/backstage-plugin-api-docs-spectral-linter maybe we could create a plugin suitable for both use cases to minimize work?
> 
> Would you be up for it?

thanks for your repo. It was a great starting point for this one.

The future of this plugin is intended for SDK generation. The plugin currently only lints using our own Spectral-based linter but we want to eventually make it auto-generate SDKs as part of an API deployment.

That being said, I don't think it makes sense to combine the two repos. Also, your repo is parameterized for custom spectral lint rules, while this one is specific to SDK generation.

**Comment by dweber019** [comment]
Your welcome 😉 

Got it, makes no sense then. Looking forward to the generation of SDK's.
